import{c as u,S as j,i as x,f as i,s as g,a as f,q as m,e as h,g as s,h as y,u as k,v as $,w,k as z,m as q,o as B}from"./svelte.js";import"./index.js";function E(e){f(e,"svelte-18o48rj",`:host{display:inline-flex}.jp-button.svelte-18o48rj{position:relative;display:inline-flex;align-items:center;justify-content:center;height:36px;border:none;outline:none;cursor:pointer;-webkit-user-select:none;-moz-user-select:none;user-select:none;vertical-align:middle;text-decoration:none;background:none;color:inherit;font-family:inherit;font-size:0.875rem;line-height:1.5;text-transform:uppercase;overflow:hidden}.jp-button.svelte-18o48rj:disabled{pointer-events:none}.jp-button.svelte-18o48rj:not(.jp-icon-button):not(.jp-fab-button):not(.jp-mini-fab-button){border-radius:0.25rem;min-width:4rem;height:2.25rem;padding:0 1rem}.jp-button.svelte-18o48rj:not(.jp-basic-button):not(.jp-raised-button):not(.jp-stroked-button):not(
      .jp-flat-button
    ){overflow:hidden;border-radius:50%}.jp-button.svelte-18o48rj::after{content:'';position:absolute;top:0;left:0;width:100%;height:100%;opacity:0.1}.jp-button.default.svelte-18o48rj:hover::after{background-color:var(--text-primary)}.jp-button.primary.svelte-18o48rj:hover::after{background-color:var(--primary-color)}.jp-button.accent.svelte-18o48rj:hover::after{background-color:var(--secondary-color)}.jp-button.warn.svelte-18o48rj:hover::after{background-color:var(--danger-color)}.jp-basic-button.svelte-18o48rj{background-color:transparent}.jp-basic-button.default.svelte-18o48rj{color:var(--text-primary)}.jp-basic-button.primary.svelte-18o48rj{color:var(--primary-color)}.jp-basic-button.accent.svelte-18o48rj{color:var(--secondary-color)}.jp-basic-button.warn.svelte-18o48rj{color:var(--danger-color)}.jp-basic-button.svelte-18o48rj:disabled{color:var(--disabled-color)}.jp-raised-button.svelte-18o48rj:not(:disabled){box-shadow:0 3px 1px -2px rgba(0, 0, 0, 0.2),
      0 2px 2px 0 rgba(0, 0, 0, 0.14),
      0 1px 5px 0 rgba(0, 0, 0, 0.12);transition:box-shadow 280ms cubic-bezier(0.4, 0, 0.2, 1)}.jp-raised-button.svelte-18o48rj:not(:disabled):hover{box-shadow:0 2px 4px -1px rgba(0, 0, 0, 0.2),
      0 4px 5px 0 rgba(0, 0, 0, 0.14),
      0 1px 10px 0 rgba(0, 0, 0, 0.12)}.jp-raised-button.svelte-18o48rj:not(:disabled):active{box-shadow:0 5px 5px -3px rgba(0, 0, 0, 0.2),
      0 8px 10px 1px rgba(0, 0, 0, 0.14),
      0 3px 14px 2px rgba(0, 0, 0, 0.12)}.jp-raised-button.default.svelte-18o48rj{background-color:var(--background-primary);color:var(--text-primary)}.jp-raised-button.primary.svelte-18o48rj{background-color:var(--primary-color);color:var(--text-on-primary)}.jp-raised-button.accent.svelte-18o48rj{background-color:var(--secondary-color);color:var(--text-on-secondary)}.jp-raised-button.warn.svelte-18o48rj{background-color:var(--danger-color);color:var(--text-on-danger)}.jp-raised-button.svelte-18o48rj:disabled{background-color:var(--background-disabled);color:var(--disabled-color)}.jp-stroked-button.svelte-18o48rj{border:1px solid var(--border-primary)}.jp-stroked-button.default.svelte-18o48rj{color:var(--text-primary)}.jp-stroked-button.primary.svelte-18o48rj{color:var(--primary-color)}.jp-stroked-button.accent.svelte-18o48rj{color:var(--secondary-color)}.jp-stroked-button.warn.svelte-18o48rj{color:var(--danger-color)}.jp-stroked-button.svelte-18o48rj:disabled{color:var(--disabled-color)}.jp-flat-button.primary.svelte-18o48rj:active::after,.jp-flat-button.accent.svelte-18o48rj:active::after,.jp-flat-button.warn.svelte-18o48rj:active::after{background-color:var(--background-primary)}.jp-flat-button.default.svelte-18o48rj{background-color:var(--background-primary);color:var(--text-primary)}.jp-flat-button.primary.svelte-18o48rj{background-color:var(--primary-color);color:var(--text-on-primary)}.jp-flat-button.accent.svelte-18o48rj{background-color:var(--secondary-color);color:var(--text-on-secondary)}.jp-flat-button.warn.svelte-18o48rj{background-color:var(--danger-color);color:var(--text-on-danger)}.jp-flat-button.svelte-18o48rj:disabled{background-color:var(--background-disabled);color:var(--disabled-color)}.jp-icon-button.svelte-18o48rj{width:3rem;height:3rem}.jp-icon-button.default.svelte-18o48rj{color:var(--text-primary);fill:var(--text-primary)}.jp-icon-button.primary.svelte-18o48rj{color:var(--primary-color);fill:var(--primary-color)}.jp-icon-button.accent.svelte-18o48rj{color:var(--secondary-color);fill:var(--secondary-color)}.jp-icon-button.warn.svelte-18o48rj{color:var(--danger-color);fill:var(--danger-color)}.jp-icon-button.svelte-18o48rj:disabled{color:var(--disabled-color);fill:var(--disabled-color)}.jp-fab-button.svelte-18o48rj{width:3.5rem;height:3.5rem}.jp-fab-button.svelte-18o48rj:not(:disabled){box-shadow:0 3px 5px -1px rgba(0, 0, 0, 0.2),
      0 6px 10px 0 rgba(0, 0, 0, 0.14),
      0 1px 18px 0 rgba(0, 0, 0, 0.12)}.jp-fab-button.svelte-18o48rj:not(:disabled):hover{box-shadow:0 5px 5px -3px rgba(0, 0, 0, 0.2),
      0 8px 10px 1px rgba(0, 0, 0, 0.14),
      0 3px 14px 2px rgba(0, 0, 0, 0.12)}.jp-fab-button.svelte-18o48rj:not(:disabled):active{box-shadow:0 7px 8px -4px rgba(0, 0, 0, 0.2),
      0 12px 17px 2px rgba(0, 0, 0, 0.14),
      0 5px 22px 4px rgba(0, 0, 0, 0.12)}.jp-fab-button.default.svelte-18o48rj{background-color:var(--background-primary)}.jp-fab-button.primary.svelte-18o48rj{background-color:var(--primary-color);color:var(--text-on-primary)}.jp-fab-button.accent.svelte-18o48rj{background-color:var(--secondary-color);color:var(--text-on-secondary)}.jp-fab-button.warn.svelte-18o48rj{background-color:var(--danger-color);color:var(--text-on-danger)}.jp-fab-button.svelte-18o48rj:disabled{background-color:var(--background-disabled);color:var(--disabled-color)}.jp-mini-fab-button.svelte-18o48rj{width:2.5rem;height:2.5rem}.jp-mini-fab-button.svelte-18o48rj:not(:disabled){box-shadow:0 3px 5px -1px rgba(0, 0, 0, 0.2),
      0 6px 10px 0 rgba(0, 0, 0, 0.14),
      0 1px 18px 0 rgba(0, 0, 0, 0.12)}.jp-mini-fab-button.svelte-18o48rj:not(:disabled):hover{box-shadow:0 5px 5px -3px rgba(0, 0, 0, 0.2),
      0 8px 10px 1px rgba(0, 0, 0, 0.14),
      0 3px 14px 2px rgba(0, 0, 0, 0.12)}.jp-mini-fab-button.svelte-18o48rj:not(:disabled):active{box-shadow:0 7px 8px -4px rgba(0, 0, 0, 0.2),
      0 12px 17px 2px rgba(0, 0, 0, 0.14),
      0 5px 22px 4px rgba(0, 0, 0, 0.12)}.jp-mini-fab-button.default.svelte-18o48rj{background-color:var(--background-primary);color:var(--text-primary)}.jp-mini-fab-button.primary.svelte-18o48rj{background-color:var(--primary-color);color:var(--text-on-primary)}.jp-mini-fab-button.accent.svelte-18o48rj{background-color:var(--secondary-color);color:var(--text-on-secondary)}.jp-mini-fab-button.warn.svelte-18o48rj{background-color:var(--danger-color);color:var(--text-on-danger)}.jp-mini-fab-button.svelte-18o48rj:disabled{background-color:var(--background-disabled);color:var(--disabled-color)}`)}function S(e){let r,n,a;const b=e[6].default,t=m(b,e,e[5],null);return{c(){r=h("a"),t&&t.c(),s(r,"href",e[3]),s(r,"target",e[4]),s(r,"disabled",e[0]),s(r,"class",n="jp-button jp-"+e[1]+"-button "+e[2]+" svelte-18o48rj")},m(o,c){y(o,r,c),t&&t.m(r,null),a=!0},p(o,[c]){t&&t.p&&(!a||c&32)&&k(t,b,o,o[5],a?w(b,o[5],c,null):$(o[5]),null),(!a||c&8)&&s(r,"href",o[3]),(!a||c&16)&&s(r,"target",o[4]),(!a||c&1)&&s(r,"disabled",o[0]),(!a||c&6&&n!==(n="jp-button jp-"+o[1]+"-button "+o[2]+" svelte-18o48rj"))&&s(r,"class",n)},i(o){a||(z(t,o),a=!0)},o(o){q(t,o),a=!1},d(o){o&&B(r),t&&t.d(o)}}}function C(e,r,n){let{$$slots:a={},$$scope:b}=r,{disabled:t=!1}=r,{variant:o="basic"}=r,{color:c="default"}=r,{href:d=""}=r,{target:p=""}=r;return e.$$set=l=>{"disabled"in l&&n(0,t=l.disabled),"variant"in l&&n(1,o=l.variant),"color"in l&&n(2,c=l.color),"href"in l&&n(3,d=l.href),"target"in l&&n(4,p=l.target),"$$scope"in l&&n(5,b=l.$$scope)},[t,o,c,d,p,b,a]}class v extends j{constructor(r){super(),x(this,r,C,S,g,{disabled:0,variant:1,color:2,href:3,target:4},E)}get disabled(){return this.$$.ctx[0]}set disabled(r){this.$$set({disabled:r}),i()}get variant(){return this.$$.ctx[1]}set variant(r){this.$$set({variant:r}),i()}get color(){return this.$$.ctx[2]}set color(r){this.$$set({color:r}),i()}get href(){return this.$$.ctx[3]}set href(r){this.$$set({href:r}),i()}get target(){return this.$$.ctx[4]}set target(r){this.$$set({target:r}),i()}}try{customElements.define("jp-link",u(v,{disabled:{type:"Boolean"},variant:{},color:{},href:{},target:{}},["default"],[],!0));}catch{};export{v as default};
//# sourceMappingURL=link.wc.js.map
