export default () => {
  import('./src/table/table.wc.svelte');
  import('./src/async-table/async-table.wc.svelte');
  import('./src/button/button.wc.svelte');
  import('./src/link/link.wc.svelte');
  import('./src/image-upload/image-upload.wc.svelte');
  import('./src/slider/slider.wc.svelte');
  import('./src/alert/alert.wc.svelte');
  import('./src/alert/render-alert');
  import('./src/confirm/confirm.wc.svelte');
  import('./src/confirm/render-confirm');
  import('./src/progress-spinner/progress-spinner.wc.svelte');
  import('./src/form-fields/input.wc.svelte');
  import('./src/form-fields/quill.wc.svelte');
  import('./src/form-fields/checkbox.wc.svelte');
  import('./src/form-fields/chips.wc.svelte');
  import('./src/form-fields/multiselect.wc.svelte');
  import('./src/form-fields/select.wc.svelte');
  import('./src/form-fields/radio.wc.svelte');
  import('./src/editors/json-editor.wc.svelte');
  import('./src/editors/code-editor.wc.svelte')
};