name: Deploy Docs

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'docs/**'

jobs:
  build-and-deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: docs
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm i
          npm i --save @jaspero/web-components@latest
          npm list @jaspero/web-components
      - name: Remove overflow hidden on playground
        run: |
          find node_modules/@docusaurus/theme-live-codeblock -name "*.css" -exec sed -i "s/overflow: hidden;/overflow: visible;/g" {} +
      - name: Copy Web Components
        run: |
          cp -r node_modules/@jaspero/web-components/dist static/c
          echo "t()" >> static/c/index.js
      - name: Build website
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build
